apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: eu-west-1
  version: "1.32"

nodeGroups:
  - name: ng-small
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 20
    labels:
      purpose: worker
    iam:
      withAddonPolicies:
        containerInsights: true   # ask eksctl to enable CW ContainerInsights support

